/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class FetchMessageStatusReq : TBase
{
  private List<long> _MessageIds;
  private List<long> _UserRelationRequestIds;

  public List<long> MessageIds
  {
    get
    {
      return _MessageIds;
    }
    set
    {
      __isset.MessageIds = true;
      this._MessageIds = value;
    }
  }

  public List<long> UserRelationRequestIds
  {
    get
    {
      return _UserRelationRequestIds;
    }
    set
    {
      __isset.UserRelationRequestIds = true;
      this._UserRelationRequestIds = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool MessageIds;
    public bool UserRelationRequestIds;
  }

  public FetchMessageStatusReq() {
  }

  public void Read (TProtocol iprot)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.List) {
              {
                MessageIds = new List<long>();
                TList _list10 = iprot.ReadListBegin();
                for( int _i11 = 0; _i11 < _list10.Count; ++_i11)
                {
                  long _elem12;
                  _elem12 = iprot.ReadI64();
                  MessageIds.Add(_elem12);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.List) {
              {
                UserRelationRequestIds = new List<long>();
                TList _list13 = iprot.ReadListBegin();
                for( int _i14 = 0; _i14 < _list13.Count; ++_i14)
                {
                  long _elem15;
                  _elem15 = iprot.ReadI64();
                  UserRelationRequestIds.Add(_elem15);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public void Write(TProtocol oprot) {
    oprot.IncrementRecursionDepth();
    try
    {
      TStruct struc = new TStruct("FetchMessageStatusReq");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (MessageIds != null && __isset.MessageIds) {
        field.Name = "MessageIds";
        field.Type = TType.List;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.I64, MessageIds.Count));
          foreach (long _iter16 in MessageIds)
          {
            oprot.WriteI64(_iter16);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      if (UserRelationRequestIds != null && __isset.UserRelationRequestIds) {
        field.Name = "UserRelationRequestIds";
        field.Type = TType.List;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.I64, UserRelationRequestIds.Count));
          foreach (long _iter17 in UserRelationRequestIds)
          {
            oprot.WriteI64(_iter17);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override string ToString() {
    StringBuilder __sb = new StringBuilder("FetchMessageStatusReq(");
    bool __first = true;
    if (MessageIds != null && __isset.MessageIds) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("MessageIds: ");
      __sb.Append(MessageIds);
    }
    if (UserRelationRequestIds != null && __isset.UserRelationRequestIds) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("UserRelationRequestIds: ");
      __sb.Append(UserRelationRequestIds);
    }
    __sb.Append(")");
    return __sb.ToString();
  }

}

