/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class FetchFriendsListResp : TBase
{
  private List<long> _OnlineUserIds;
  private List<long> _OfflineUserIds;

  public List<long> OnlineUserIds
  {
    get
    {
      return _OnlineUserIds;
    }
    set
    {
      __isset.OnlineUserIds = true;
      this._OnlineUserIds = value;
    }
  }

  public List<long> OfflineUserIds
  {
    get
    {
      return _OfflineUserIds;
    }
    set
    {
      __isset.OfflineUserIds = true;
      this._OfflineUserIds = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool OnlineUserIds;
    public bool OfflineUserIds;
  }

  public FetchFriendsListResp() {
  }

  public void Read (TProtocol iprot)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.List) {
              {
                OnlineUserIds = new List<long>();
                TList _list28 = iprot.ReadListBegin();
                for( int _i29 = 0; _i29 < _list28.Count; ++_i29)
                {
                  long _elem30;
                  _elem30 = iprot.ReadI64();
                  OnlineUserIds.Add(_elem30);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.List) {
              {
                OfflineUserIds = new List<long>();
                TList _list31 = iprot.ReadListBegin();
                for( int _i32 = 0; _i32 < _list31.Count; ++_i32)
                {
                  long _elem33;
                  _elem33 = iprot.ReadI64();
                  OfflineUserIds.Add(_elem33);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public void Write(TProtocol oprot) {
    oprot.IncrementRecursionDepth();
    try
    {
      TStruct struc = new TStruct("FetchFriendsListResp");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (OnlineUserIds != null && __isset.OnlineUserIds) {
        field.Name = "OnlineUserIds";
        field.Type = TType.List;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.I64, OnlineUserIds.Count));
          foreach (long _iter34 in OnlineUserIds)
          {
            oprot.WriteI64(_iter34);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      if (OfflineUserIds != null && __isset.OfflineUserIds) {
        field.Name = "OfflineUserIds";
        field.Type = TType.List;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.I64, OfflineUserIds.Count));
          foreach (long _iter35 in OfflineUserIds)
          {
            oprot.WriteI64(_iter35);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override string ToString() {
    StringBuilder __sb = new StringBuilder("FetchFriendsListResp(");
    bool __first = true;
    if (OnlineUserIds != null && __isset.OnlineUserIds) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("OnlineUserIds: ");
      __sb.Append(OnlineUserIds);
    }
    if (OfflineUserIds != null && __isset.OfflineUserIds) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("OfflineUserIds: ");
      __sb.Append(OfflineUserIds);
    }
    __sb.Append(")");
    return __sb.ToString();
  }

}

