/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class FetchOfflineMessageResp : TBase
{
  private List<Message> _Messages;
  private List<UserRelation> _UserRelations;

  public List<Message> Messages
  {
    get
    {
      return _Messages;
    }
    set
    {
      __isset.Messages = true;
      this._Messages = value;
    }
  }

  public List<UserRelation> UserRelations
  {
    get
    {
      return _UserRelations;
    }
    set
    {
      __isset.UserRelations = true;
      this._UserRelations = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool Messages;
    public bool UserRelations;
  }

  public FetchOfflineMessageResp() {
  }

  public void Read (TProtocol iprot)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.List) {
              {
                Messages = new List<Message>();
                TList _list8 = iprot.ReadListBegin();
                for( int _i9 = 0; _i9 < _list8.Count; ++_i9)
                {
                  Message _elem10;
                  _elem10 = new Message();
                  _elem10.Read(iprot);
                  Messages.Add(_elem10);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.List) {
              {
                UserRelations = new List<UserRelation>();
                TList _list11 = iprot.ReadListBegin();
                for( int _i12 = 0; _i12 < _list11.Count; ++_i12)
                {
                  UserRelation _elem13;
                  _elem13 = new UserRelation();
                  _elem13.Read(iprot);
                  UserRelations.Add(_elem13);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public void Write(TProtocol oprot) {
    oprot.IncrementRecursionDepth();
    try
    {
      TStruct struc = new TStruct("FetchOfflineMessageResp");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (Messages != null && __isset.Messages) {
        field.Name = "Messages";
        field.Type = TType.List;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, Messages.Count));
          foreach (Message _iter14 in Messages)
          {
            _iter14.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      if (UserRelations != null && __isset.UserRelations) {
        field.Name = "UserRelations";
        field.Type = TType.List;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, UserRelations.Count));
          foreach (UserRelation _iter15 in UserRelations)
          {
            _iter15.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override string ToString() {
    StringBuilder __sb = new StringBuilder("FetchOfflineMessageResp(");
    bool __first = true;
    if (Messages != null && __isset.Messages) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Messages: ");
      __sb.Append(Messages);
    }
    if (UserRelations != null && __isset.UserRelations) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("UserRelations: ");
      __sb.Append(UserRelations);
    }
    __sb.Append(")");
    return __sb.ToString();
  }

}

