/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class GetSTSInfoResp : TBase
{
  private string _SecurityToken;
  private string _AccessKeyId;
  private string _AccessKeySecret;

  public string SecurityToken
  {
    get
    {
      return _SecurityToken;
    }
    set
    {
      __isset.SecurityToken = true;
      this._SecurityToken = value;
    }
  }

  public string AccessKeyId
  {
    get
    {
      return _AccessKeyId;
    }
    set
    {
      __isset.AccessKeyId = true;
      this._AccessKeyId = value;
    }
  }

  public string AccessKeySecret
  {
    get
    {
      return _AccessKeySecret;
    }
    set
    {
      __isset.AccessKeySecret = true;
      this._AccessKeySecret = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool SecurityToken;
    public bool AccessKeyId;
    public bool AccessKeySecret;
  }

  public GetSTSInfoResp() {
  }

  public void Read (TProtocol iprot)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String) {
              SecurityToken = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.String) {
              AccessKeyId = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.String) {
              AccessKeySecret = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public void Write(TProtocol oprot) {
    oprot.IncrementRecursionDepth();
    try
    {
      TStruct struc = new TStruct("GetSTSInfoResp");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (SecurityToken != null && __isset.SecurityToken) {
        field.Name = "SecurityToken";
        field.Type = TType.String;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(SecurityToken);
        oprot.WriteFieldEnd();
      }
      if (AccessKeyId != null && __isset.AccessKeyId) {
        field.Name = "AccessKeyId";
        field.Type = TType.String;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(AccessKeyId);
        oprot.WriteFieldEnd();
      }
      if (AccessKeySecret != null && __isset.AccessKeySecret) {
        field.Name = "AccessKeySecret";
        field.Type = TType.String;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(AccessKeySecret);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override string ToString() {
    StringBuilder __sb = new StringBuilder("GetSTSInfoResp(");
    bool __first = true;
    if (SecurityToken != null && __isset.SecurityToken) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("SecurityToken: ");
      __sb.Append(SecurityToken);
    }
    if (AccessKeyId != null && __isset.AccessKeyId) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("AccessKeyId: ");
      __sb.Append(AccessKeyId);
    }
    if (AccessKeySecret != null && __isset.AccessKeySecret) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("AccessKeySecret: ");
      __sb.Append(AccessKeySecret);
    }
    __sb.Append(")");
    return __sb.ToString();
  }

}

