/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class SyncMessageReq : TBase
{
  private long _UserId;
  private long _MessageId;
  private long _UserRelationId;

  public long UserId
  {
    get
    {
      return _UserId;
    }
    set
    {
      __isset.UserId = true;
      this._UserId = value;
    }
  }

  public long MessageId
  {
    get
    {
      return _MessageId;
    }
    set
    {
      __isset.MessageId = true;
      this._MessageId = value;
    }
  }

  public long UserRelationId
  {
    get
    {
      return _UserRelationId;
    }
    set
    {
      __isset.UserRelationId = true;
      this._UserRelationId = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool UserId;
    public bool MessageId;
    public bool UserRelationId;
  }

  public SyncMessageReq() {
  }

  public void Read (TProtocol iprot)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I64) {
              UserId = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I64) {
              MessageId = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.I64) {
              UserRelationId = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public void Write(TProtocol oprot) {
    oprot.IncrementRecursionDepth();
    try
    {
      TStruct struc = new TStruct("SyncMessageReq");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.UserId) {
        field.Name = "UserId";
        field.Type = TType.I64;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(UserId);
        oprot.WriteFieldEnd();
      }
      if (__isset.MessageId) {
        field.Name = "MessageId";
        field.Type = TType.I64;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(MessageId);
        oprot.WriteFieldEnd();
      }
      if (__isset.UserRelationId) {
        field.Name = "UserRelationId";
        field.Type = TType.I64;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(UserRelationId);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override string ToString() {
    StringBuilder __sb = new StringBuilder("SyncMessageReq(");
    bool __first = true;
    if (__isset.UserId) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("UserId: ");
      __sb.Append(UserId);
    }
    if (__isset.MessageId) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("MessageId: ");
      __sb.Append(MessageId);
    }
    if (__isset.UserRelationId) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("UserRelationId: ");
      __sb.Append(UserRelationId);
    }
    __sb.Append(")");
    return __sb.ToString();
  }

}

