/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class UpdateMessageStatusReq : TBase
{
  private Dictionary<long, int> _MessageIds;
  private Dictionary<long, int> _UserRelationRequestIds;

  public Dictionary<long, int> MessageIds
  {
    get
    {
      return _MessageIds;
    }
    set
    {
      __isset.MessageIds = true;
      this._MessageIds = value;
    }
  }

  public Dictionary<long, int> UserRelationRequestIds
  {
    get
    {
      return _UserRelationRequestIds;
    }
    set
    {
      __isset.UserRelationRequestIds = true;
      this._UserRelationRequestIds = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool MessageIds;
    public bool UserRelationRequestIds;
  }

  public UpdateMessageStatusReq() {
  }

  public void Read (TProtocol iprot)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Map) {
              {
                MessageIds = new Dictionary<long, int>();
                TMap _map0 = iprot.ReadMapBegin();
                for( int _i1 = 0; _i1 < _map0.Count; ++_i1)
                {
                  long _key2;
                  int _val3;
                  _key2 = iprot.ReadI64();
                  _val3 = iprot.ReadI32();
                  MessageIds[_key2] = _val3;
                }
                iprot.ReadMapEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.Map) {
              {
                UserRelationRequestIds = new Dictionary<long, int>();
                TMap _map4 = iprot.ReadMapBegin();
                for( int _i5 = 0; _i5 < _map4.Count; ++_i5)
                {
                  long _key6;
                  int _val7;
                  _key6 = iprot.ReadI64();
                  _val7 = iprot.ReadI32();
                  UserRelationRequestIds[_key6] = _val7;
                }
                iprot.ReadMapEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public void Write(TProtocol oprot) {
    oprot.IncrementRecursionDepth();
    try
    {
      TStruct struc = new TStruct("UpdateMessageStatusReq");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (MessageIds != null && __isset.MessageIds) {
        field.Name = "MessageIds";
        field.Type = TType.Map;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteMapBegin(new TMap(TType.I64, TType.I32, MessageIds.Count));
          foreach (long _iter8 in MessageIds.Keys)
          {
            oprot.WriteI64(_iter8);
            oprot.WriteI32(MessageIds[_iter8]);
          }
          oprot.WriteMapEnd();
        }
        oprot.WriteFieldEnd();
      }
      if (UserRelationRequestIds != null && __isset.UserRelationRequestIds) {
        field.Name = "UserRelationRequestIds";
        field.Type = TType.Map;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteMapBegin(new TMap(TType.I64, TType.I32, UserRelationRequestIds.Count));
          foreach (long _iter9 in UserRelationRequestIds.Keys)
          {
            oprot.WriteI64(_iter9);
            oprot.WriteI32(UserRelationRequestIds[_iter9]);
          }
          oprot.WriteMapEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override string ToString() {
    StringBuilder __sb = new StringBuilder("UpdateMessageStatusReq(");
    bool __first = true;
    if (MessageIds != null && __isset.MessageIds) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("MessageIds: ");
      __sb.Append(MessageIds);
    }
    if (UserRelationRequestIds != null && __isset.UserRelationRequestIds) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("UserRelationRequestIds: ");
      __sb.Append(UserRelationRequestIds);
    }
    __sb.Append(")");
    return __sb.ToString();
  }

}

