/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class DeleteFriendReq : TBase
{
  private long _UserIdSend;
  private long _UserIdRecv;

  public long UserIdSend
  {
    get
    {
      return _UserIdSend;
    }
    set
    {
      __isset.UserIdSend = true;
      this._UserIdSend = value;
    }
  }

  public long UserIdRecv
  {
    get
    {
      return _UserIdRecv;
    }
    set
    {
      __isset.UserIdRecv = true;
      this._UserIdRecv = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool UserIdSend;
    public bool UserIdRecv;
  }

  public DeleteFriendReq() {
  }

  public void Read (TProtocol iprot)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I64) {
              UserIdSend = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I64) {
              UserIdRecv = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public void Write(TProtocol oprot) {
    oprot.IncrementRecursionDepth();
    try
    {
      TStruct struc = new TStruct("DeleteFriendReq");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.UserIdSend) {
        field.Name = "UserIdSend";
        field.Type = TType.I64;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(UserIdSend);
        oprot.WriteFieldEnd();
      }
      if (__isset.UserIdRecv) {
        field.Name = "UserIdRecv";
        field.Type = TType.I64;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(UserIdRecv);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override string ToString() {
    StringBuilder __sb = new StringBuilder("DeleteFriendReq(");
    bool __first = true;
    if (__isset.UserIdSend) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("UserIdSend: ");
      __sb.Append(UserIdSend);
    }
    if (__isset.UserIdRecv) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("UserIdRecv: ");
      __sb.Append(UserIdRecv);
    }
    __sb.Append(")");
    return __sb.ToString();
  }

}

