/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class Message : TBase
{
  private long _Id;
  private long _UserIdSend;
  private long _UserIdRecv;
  private long _GroupId;
  private string _Content;
  private long _CreateTime;
  private int _MsgType;
  private int _IsRead;

  public long Id
  {
    get
    {
      return _Id;
    }
    set
    {
      __isset.Id = true;
      this._Id = value;
    }
  }

  public long UserIdSend
  {
    get
    {
      return _UserIdSend;
    }
    set
    {
      __isset.UserIdSend = true;
      this._UserIdSend = value;
    }
  }

  public long UserIdRecv
  {
    get
    {
      return _UserIdRecv;
    }
    set
    {
      __isset.UserIdRecv = true;
      this._UserIdRecv = value;
    }
  }

  public long GroupId
  {
    get
    {
      return _GroupId;
    }
    set
    {
      __isset.GroupId = true;
      this._GroupId = value;
    }
  }

  public string Content
  {
    get
    {
      return _Content;
    }
    set
    {
      __isset.Content = true;
      this._Content = value;
    }
  }

  public long CreateTime
  {
    get
    {
      return _CreateTime;
    }
    set
    {
      __isset.CreateTime = true;
      this._CreateTime = value;
    }
  }

  public int MsgType
  {
    get
    {
      return _MsgType;
    }
    set
    {
      __isset.MsgType = true;
      this._MsgType = value;
    }
  }

  public int IsRead
  {
    get
    {
      return _IsRead;
    }
    set
    {
      __isset.IsRead = true;
      this._IsRead = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool Id;
    public bool UserIdSend;
    public bool UserIdRecv;
    public bool GroupId;
    public bool Content;
    public bool CreateTime;
    public bool MsgType;
    public bool IsRead;
  }

  public Message() {
  }

  public void Read (TProtocol iprot)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I64) {
              Id = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I64) {
              UserIdSend = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.I64) {
              UserIdRecv = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.I64) {
              GroupId = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 5:
            if (field.Type == TType.String) {
              Content = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 6:
            if (field.Type == TType.I64) {
              CreateTime = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 7:
            if (field.Type == TType.I32) {
              MsgType = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 8:
            if (field.Type == TType.I32) {
              IsRead = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public void Write(TProtocol oprot) {
    oprot.IncrementRecursionDepth();
    try
    {
      TStruct struc = new TStruct("Message");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.Id) {
        field.Name = "Id";
        field.Type = TType.I64;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(Id);
        oprot.WriteFieldEnd();
      }
      if (__isset.UserIdSend) {
        field.Name = "UserIdSend";
        field.Type = TType.I64;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(UserIdSend);
        oprot.WriteFieldEnd();
      }
      if (__isset.UserIdRecv) {
        field.Name = "UserIdRecv";
        field.Type = TType.I64;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(UserIdRecv);
        oprot.WriteFieldEnd();
      }
      if (__isset.GroupId) {
        field.Name = "GroupId";
        field.Type = TType.I64;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(GroupId);
        oprot.WriteFieldEnd();
      }
      if (Content != null && __isset.Content) {
        field.Name = "Content";
        field.Type = TType.String;
        field.ID = 5;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Content);
        oprot.WriteFieldEnd();
      }
      if (__isset.CreateTime) {
        field.Name = "CreateTime";
        field.Type = TType.I64;
        field.ID = 6;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(CreateTime);
        oprot.WriteFieldEnd();
      }
      if (__isset.MsgType) {
        field.Name = "MsgType";
        field.Type = TType.I32;
        field.ID = 7;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(MsgType);
        oprot.WriteFieldEnd();
      }
      if (__isset.IsRead) {
        field.Name = "IsRead";
        field.Type = TType.I32;
        field.ID = 8;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(IsRead);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override string ToString() {
    StringBuilder __sb = new StringBuilder("Message(");
    bool __first = true;
    if (__isset.Id) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Id: ");
      __sb.Append(Id);
    }
    if (__isset.UserIdSend) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("UserIdSend: ");
      __sb.Append(UserIdSend);
    }
    if (__isset.UserIdRecv) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("UserIdRecv: ");
      __sb.Append(UserIdRecv);
    }
    if (__isset.GroupId) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("GroupId: ");
      __sb.Append(GroupId);
    }
    if (Content != null && __isset.Content) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Content: ");
      __sb.Append(Content);
    }
    if (__isset.CreateTime) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("CreateTime: ");
      __sb.Append(CreateTime);
    }
    if (__isset.MsgType) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("MsgType: ");
      __sb.Append(MsgType);
    }
    if (__isset.IsRead) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("IsRead: ");
      __sb.Append(IsRead);
    }
    __sb.Append(")");
    return __sb.ToString();
  }

}

