/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class SyncMessageResp : TBase
{
  private List<Message> _Messages;
  private List<UserRelation> _UserRelations;
  private List<@Object> _Objects;
  private long _LastOnlineTime;

  public List<Message> Messages
  {
    get
    {
      return _Messages;
    }
    set
    {
      __isset.Messages = true;
      this._Messages = value;
    }
  }

  public List<UserRelation> UserRelations
  {
    get
    {
      return _UserRelations;
    }
    set
    {
      __isset.UserRelations = true;
      this._UserRelations = value;
    }
  }

  public List<@Object> Objects
  {
    get
    {
      return _Objects;
    }
    set
    {
      __isset.Objects = true;
      this._Objects = value;
    }
  }

  public long LastOnlineTime
  {
    get
    {
      return _LastOnlineTime;
    }
    set
    {
      __isset.LastOnlineTime = true;
      this._LastOnlineTime = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool Messages;
    public bool UserRelations;
    public bool Objects;
    public bool LastOnlineTime;
  }

  public SyncMessageResp() {
  }

  public void Read (TProtocol iprot)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.List) {
              {
                Messages = new List<Message>();
                TList _list36 = iprot.ReadListBegin();
                for( int _i37 = 0; _i37 < _list36.Count; ++_i37)
                {
                  Message _elem38;
                  _elem38 = new Message();
                  _elem38.Read(iprot);
                  Messages.Add(_elem38);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.List) {
              {
                UserRelations = new List<UserRelation>();
                TList _list39 = iprot.ReadListBegin();
                for( int _i40 = 0; _i40 < _list39.Count; ++_i40)
                {
                  UserRelation _elem41;
                  _elem41 = new UserRelation();
                  _elem41.Read(iprot);
                  UserRelations.Add(_elem41);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.List) {
              {
                Objects = new List<@Object>();
                TList _list42 = iprot.ReadListBegin();
                for( int _i43 = 0; _i43 < _list42.Count; ++_i43)
                {
                  @Object _elem44;
                  _elem44 = new @Object();
                  _elem44.Read(iprot);
                  Objects.Add(_elem44);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.I64) {
              LastOnlineTime = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public void Write(TProtocol oprot) {
    oprot.IncrementRecursionDepth();
    try
    {
      TStruct struc = new TStruct("SyncMessageResp");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (Messages != null && __isset.Messages) {
        field.Name = "Messages";
        field.Type = TType.List;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, Messages.Count));
          foreach (Message _iter45 in Messages)
          {
            _iter45.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      if (UserRelations != null && __isset.UserRelations) {
        field.Name = "UserRelations";
        field.Type = TType.List;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, UserRelations.Count));
          foreach (UserRelation _iter46 in UserRelations)
          {
            _iter46.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      if (Objects != null && __isset.Objects) {
        field.Name = "Objects";
        field.Type = TType.List;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, Objects.Count));
          foreach (@Object _iter47 in Objects)
          {
            _iter47.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      if (__isset.LastOnlineTime) {
        field.Name = "LastOnlineTime";
        field.Type = TType.I64;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(LastOnlineTime);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override string ToString() {
    StringBuilder __sb = new StringBuilder("SyncMessageResp(");
    bool __first = true;
    if (Messages != null && __isset.Messages) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Messages: ");
      __sb.Append(Messages);
    }
    if (UserRelations != null && __isset.UserRelations) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("UserRelations: ");
      __sb.Append(UserRelations);
    }
    if (Objects != null && __isset.Objects) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Objects: ");
      __sb.Append(Objects);
    }
    if (__isset.LastOnlineTime) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("LastOnlineTime: ");
      __sb.Append(LastOnlineTime);
    }
    __sb.Append(")");
    return __sb.ToString();
  }

}

